server:
  port: 9080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9081
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://localhost:9082
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://localhost:9083
          predicates:
            - Path=/api/orders/**
  
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.tecsup.app.micro: DEBUG 